name: Build commit

on:
  push:
    branches-ignore:
      - 'v**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Publish shared library
        run: ./gradlew :pftool-shared:publish

      - name: Build with Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/key.jks
          ./gradlew packageReleaseUniversalApk -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/key.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Prepare assets
        run: |
          mv app/build/outputs/apk_from_bundle/release/app-release-universal.apk pftool.apk
          mv app/build/outputs/mapping/release/mapping.txt mapping.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: pftool
          path: |
            pftool.apk
            mapping.txt